# _config.yml

url: "https://artalopa.github.io"
baseurl: "artalopa.github.io"
title: "Ryan Artalopa"

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
